### PR TITLE
Fix sample code

### PR DESCRIPTION
**Pull request by FokkeZB**
@hansemannn indentation made it unformatted on:
http://docs.appcelerator.com/platform/latest/#!/api/Modules.SafariDialog

### CODE REVIEW

**Comment by hansemannn** [comment]
@FokkeZB The provided link does not work.

**Comment by FokkeZB** [comment]
Yes :(
https://jira.appcelerator.org/browse/TIDOC-2385

**Comment by hansemannn** [comment]
Alright! PR still looks good, merging. Will wait for the next module fixes / features before updating the ti-master, since it isn't a code-change. Cool?

**Comment by FokkeZB** [comment]
Sure!

**Pull request merged**
